2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/collection_view@1.3x.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/collection_view.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 396 X 322
2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/intellishell@1.3x.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/intellishell.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 396 X 322
2020-01-23 00:04:27 [main] t3.utils.be.readWinRegistry()
WARNING: Unable to fetch value of type REG_DWORD for key AppsUseLightTheme from registry at HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/light_theme@1.3x.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/light_theme.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 396 X 322
2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/dark_theme@1.3x.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/dark_theme.png
2020-01-23 00:04:27 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 396 X 322
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/connect@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/connect.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database_server@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database_server.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/collection@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/collection.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/find@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/find.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/import_tn@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/import_tn.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/export_tn@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/export_tn.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_migration@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_migration.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/aggregation_gt@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/aggregation_gt.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/intellishell_gt@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/intellishell_gt.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_gt@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_gt.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/users/24x24/group_3t@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/users/24x24/group_3t.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/24x24/script_key_3t@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/24x24/script_key_3t.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/chart_pie@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/chart_pie.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/edit_diff@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/edit_diff.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/task@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/task.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/feedback@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/feedback.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/se/24x24/run@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/se/24x24/run.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/intellishell_gt@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/intellishell_gt.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/sql_gt@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/sql_gt.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/open@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/open.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save_as@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save_as.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/aggregation@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/aggregation.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/map_reduce_tz@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/map_reduce_tz.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/chart_pie@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/chart_pie.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/edit_diff@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/edit_diff.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/collection@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/collection.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/map_reduce_tz@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/map_reduce_tz.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/cross-circle-frame@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/cross-circle-frame.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_right_edited@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_right_edited.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/view_tz@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/view_tz.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/new_collection_tz@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/new_collection_tz.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/code@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/code.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/gridfs@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/gridfs.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/users@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/users.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/16x16/script_key@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/16x16/script_key.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/index@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/index.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/sessions@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/sessions.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/replica_set@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/replica_set.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_primary_v4@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_primary_v4.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_secondary_v4@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_secondary_v4.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fugue/16x16/folder-horizontal@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fugue/16x16/folder-horizontal.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/folder@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/folder.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_left_edited@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_left_edited.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/draw_eraser@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/draw_eraser.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_down_edited@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_down_edited.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_up_edited@1.3x.png
2020-01-23 00:04:56 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_up_edited.png
2020-01-23 00:04:56 [main] t3.utils.u.q.ayN()
WARNING: Cannot read managed property store from disk: java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
	at t3.utils.u.q.ayN(ManagedPropertyStore.java:228)
	at t3.utils.u.aa.get(PropertyStore.java:248)
	at t3.utils.u.aa.get(PropertyStore.java:245)
	at t3.utils.u.w.a(PropertyStore.java:64)
	at t3.utils.u.v.a(PropertyStore.java:245)
	at t3.utils.u.q.read(ManagedPropertyStore.java:224)
	at t3.utils.u.q.a(ManagedPropertyStore.java:128)
	at t3.utils.u.q.ni(ManagedPropertyStore.java:87)
	at t3.utils.u.k.<clinit>(DefaultTrustedPropertyStore.java:16)
	at t3.utils.connman.ew.bD(MongoConnectionInfoRestrictions.java:76)
	at t3.utils.connman.ew.Ql(MongoConnectionInfoRestrictions.java:147)
	at t3.utils.connman.ew.<init>(MongoConnectionInfoRestrictions.java:43)
	at t3.utils.connman.by.<init>(ConnectionManager.java:98)
	at t3.utils.connman.by.Ot(ConnectionManager.java:106)
	at t3.dataman.mongodb.app.a.<init>(AppController.java:135)
	at t3.dataman.mongodb.app.ad.main(AppRunner.java:118)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/galleries/arrow_left@1.3x.png
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/galleries/arrow_left.png
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/galleries/arrow_right@1.3x.png
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/galleries/arrow_right.png
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/galleries/bullet_white@1.3x.png
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/galleries/bullet_white.png
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/galleries/bullet_green@1.3x.png
2020-01-23 00:04:57 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/galleries/bullet_green.png
2020-01-23 00:05:12 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/color_swatches@1.3x.png
2020-01-23 00:05:12 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/color_swatches.png
2020-01-23 00:05:13 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/information-3t@1.3x.png
2020-01-23 00:05:13 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/information-3t.png
2020-01-23 00:05:13 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/16x16/eye@1.3x.png
2020-01-23 00:05:13 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/16x16/eye.png
2020-01-23 00:05:13 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/folder_explore@1.3x.png
2020-01-23 00:05:13 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/folder_explore.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/database_add@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/database_add.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/folder_add@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/folder_add.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_edit@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_edit.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_delete@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_delete.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_copy@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_copy.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/import_connections@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/import_connections.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/export_connections@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/export_connections.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/20x16/database_server@1.3x.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/20x16/database_server.png
2020-01-23 00:05:17 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 00:05:19 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/16x16/database_server@1.3x.png
2020-01-23 00:05:19 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/16x16/database_server.png
2020-01-23 00:05:24 [main] t3.utils.connman.fg.a()
ERROR: Update is ProgressUpdate: Connecting to server Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]: t3.utils.connman.cg: Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at t3.utils.connman.c.c.g(MongoDBConnector.java:476)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:675)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:349)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 00:05:43 [main] t3.utils.u.o.ng()
ERROR: Couldn't read UUID for cm: 
2020-01-23 00:05:49 [main] t3.utils.connman.fg.a()
ERROR: Update is ProgressUpdate: Connecting to server Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]: t3.utils.connman.cg: Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at t3.utils.connman.c.c.g(MongoDBConnector.java:476)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:675)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:349)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/connect@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/connect.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database_server@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database_server.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/collection@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/collection.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/find@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/find.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/import_tn@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/import_tn.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/export_tn@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/export_tn.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_migration@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_migration.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/aggregation_gt@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/aggregation_gt.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/intellishell_gt@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/intellishell_gt.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_gt@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_gt.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/users/24x24/group_3t@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/users/24x24/group_3t.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/24x24/script_key_3t@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/24x24/script_key_3t.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/chart_pie@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/chart_pie.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/edit_diff@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/edit_diff.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/task@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/task.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/feedback@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/feedback.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/se/24x24/run@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/se/24x24/run.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/intellishell_gt@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/intellishell_gt.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/sql_gt@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/sql_gt.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/open@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/open.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save_as@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save_as.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/aggregation@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/aggregation.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/map_reduce_tz@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/map_reduce_tz.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/chart_pie@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/chart_pie.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/edit_diff@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/edit_diff.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/collection@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/collection.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/map_reduce_tz@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/map_reduce_tz.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/cross-circle-frame@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/cross-circle-frame.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_right_edited@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_right_edited.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/view_tz@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/view_tz.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/new_collection_tz@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/new_collection_tz.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/code@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/code.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/gridfs@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/gridfs.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/users@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/users.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/16x16/script_key@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/16x16/script_key.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/index@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/index.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/sessions@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/sessions.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/replica_set@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/replica_set.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_primary_v4@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_primary_v4.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_secondary_v4@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_secondary_v4.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fugue/16x16/folder-horizontal@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fugue/16x16/folder-horizontal.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/folder@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/folder.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_left_edited@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_left_edited.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/draw_eraser@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/draw_eraser.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_down_edited@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_down_edited.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_up_edited@1.3x.png
2020-01-23 00:06:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_up_edited.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/database_add@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/database_add.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/folder_add@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/folder_add.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_edit@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_edit.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_delete@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_delete.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_copy@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_copy.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/import_connections@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/import_connections.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/export_connections@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/export_connections.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/20x16/database_server@1.3x.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/20x16/database_server.png
2020-01-23 00:06:18 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 00:06:18 [main] t3.utils.u.o.ng()
ERROR: Couldn't read UUID for cm: 
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/color_swatches@1.3x.png
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/color_swatches.png
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/information-3t@1.3x.png
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/information-3t.png
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/16x16/eye@1.3x.png
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/16x16/eye.png
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/folder_explore@1.3x.png
2020-01-23 00:06:20 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/folder_explore.png
2020-01-23 00:06:48 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/16x16/database_server@1.3x.png
2020-01-23 00:06:48 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/16x16/database_server.png
2020-01-23 00:06:53 [main] t3.utils.connman.fg.a()
ERROR: Update is ProgressUpdate: Connecting to server Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]: t3.utils.connman.cg: Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at t3.utils.connman.c.c.g(MongoDBConnector.java:476)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:675)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:349)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 00:07:24 [main] t3.utils.connman.fg.a()
ERROR: Update is ProgressUpdate: Connecting to server Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]: t3.utils.connman.cg: Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at t3.utils.connman.c.c.g(MongoDBConnector.java:476)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.dataman.mongodb.app.a.a(AppController.java:396)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:675)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:349)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.dataman.mongodb.app.a.a(AppController.java:396)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/connect@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/connect.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database_server@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database_server.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/collection@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/collection.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/find@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/find.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/import_tn@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/import_tn.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/export_tn@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/export_tn.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_migration@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_migration.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/aggregation_gt@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/aggregation_gt.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/intellishell_gt@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/intellishell_gt.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_gt@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_gt.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/users/24x24/group_3t@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/users/24x24/group_3t.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/24x24/script_key_3t@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/24x24/script_key_3t.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/chart_pie@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/chart_pie.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/edit_diff@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/edit_diff.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/task@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/task.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/feedback@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/feedback.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/se/24x24/run@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/se/24x24/run.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/intellishell_gt@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/intellishell_gt.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/sql_gt@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/sql_gt.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/open@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/open.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save_as@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save_as.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/aggregation@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/aggregation.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/map_reduce_tz@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/map_reduce_tz.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/chart_pie@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/chart_pie.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/edit_diff@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/edit_diff.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/collection@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/collection.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/map_reduce_tz@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/map_reduce_tz.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/cross-circle-frame@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/cross-circle-frame.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_right_edited@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_right_edited.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/view_tz@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/view_tz.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/new_collection_tz@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/new_collection_tz.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/code@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/code.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/gridfs@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/gridfs.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/users@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/users.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/16x16/script_key@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/16x16/script_key.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/index@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/index.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/sessions@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/sessions.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/replica_set@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/replica_set.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_primary_v4@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_primary_v4.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_secondary_v4@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_secondary_v4.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fugue/16x16/folder-horizontal@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fugue/16x16/folder-horizontal.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/folder@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/folder.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_left_edited@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_left_edited.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/draw_eraser@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/draw_eraser.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_down_edited@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_down_edited.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_up_edited@1.3x.png
2020-01-23 00:09:44 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_up_edited.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/execute@1.3x.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/execute.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/plus@1.3x.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/plus.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/minus@1.3x.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/minus.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/copy@1.3x.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/copy.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/information-3t@1.3x.png
2020-01-23 00:09:55 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/information-3t.png
2020-01-23 00:10:41 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/16x16/database_server@1.3x.png
2020-01-23 00:10:41 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/16x16/database_server.png
2020-01-23 00:10:46 [main] t3.utils.connman.fg.a()
ERROR: Update is ProgressUpdate: Connecting to server Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]: t3.utils.connman.cg: Connection failed.

SERVER [localhost:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at t3.utils.connman.c.c.g(MongoDBConnector.java:476)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.dataman.mongodb.app.a.a(AppController.java:396)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:675)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:349)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.dataman.mongodb.app.a.a(AppController.java:396)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/database_add@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/database_add.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/folder_add@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/folder_add.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_edit@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_edit.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_delete@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_delete.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_copy@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_copy.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/import_connections@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/import_connections.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/export_connections@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/export_connections.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/20x16/database_server@1.3x.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/20x16/database_server.png
2020-01-23 00:14:06 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 00:14:06 [main] t3.utils.u.o.ng()
ERROR: Couldn't read UUID for cm: 
2020-01-23 00:14:08 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/color_swatches@1.3x.png
2020-01-23 00:14:08 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/color_swatches.png
2020-01-23 00:14:08 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/16x16/eye@1.3x.png
2020-01-23 00:14:08 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/16x16/eye.png
2020-01-23 00:14:08 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/folder_explore@1.3x.png
2020-01-23 00:14:08 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/folder_explore.png
2020-01-23 00:14:35 [main] t3.utils.connman.fg.a()
ERROR: Update is ProgressUpdate: Connecting to server Connection failed.

SERVER [127.0.0.1:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]: t3.utils.connman.cg: Connection failed.

SERVER [127.0.0.1:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ Socket error: Connection refused: connect

Details:
Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at t3.utils.connman.c.c.g(MongoDBConnector.java:476)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 5000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:675)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:349)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 01:09:15 [main] t3.utils.ac.l.<init>()
ERROR: application state storage is disabled, another instance of application is already running
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/connect@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/connect.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database_server@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database_server.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/database@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/database.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/collection@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/collection.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/find@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/find.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/import_tn@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/import_tn.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/export_tn@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/export_tn.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_migration@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_migration.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/aggregation_gt@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/aggregation_gt.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/intellishell_gt@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/intellishell_gt.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/sql_gt@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/sql_gt.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/users/24x24/group_3t@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/users/24x24/group_3t.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/24x24/script_key_3t@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/24x24/script_key_3t.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/chart_pie@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/chart_pie.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/edit_diff@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/edit_diff.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/task@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/task.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/feedback@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/feedback.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/se/24x24/run@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/se/24x24/run.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/intellishell_gt@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/intellishell_gt.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/sql_gt@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/sql_gt.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/open@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/open.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/save_as@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/save_as.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/aggregation@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/aggregation.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/map_reduce_tz@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/map_reduce_tz.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/chart_pie@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/chart_pie.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/edit_diff@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/edit_diff.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/collection@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/collection.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/24x24/map_reduce_tz@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/24x24/map_reduce_tz.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/cross-circle-frame@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/cross-circle-frame.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_right_edited@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_right_edited.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/view_tz@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/view_tz.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/new_collection_tz@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/new_collection_tz.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/code@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/code.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/gridfs@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/gridfs.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/users@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/users.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/roles/16x16/script_key@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/roles/16x16/script_key.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/index@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/index.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/sessions@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/sessions.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/replica_set@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/replica_set.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_primary_v4@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_primary_v4.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/server_secondary_v4@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/server_secondary_v4.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fugue/16x16/folder-horizontal@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fugue/16x16/folder-horizontal.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/folder@1.3x.png
2020-01-23 01:09:15 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/folder.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_left_edited@1.3x.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_left_edited.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/draw_eraser@1.3x.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/draw_eraser.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_down_edited@1.3x.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_down_edited.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/level_up_edited@1.3x.png
2020-01-23 01:09:16 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/level_up_edited.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/database_add@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/database_add.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/folder_add@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/folder_add.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_edit@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_edit.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_delete@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_delete.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/page_white_copy@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/page_white_copy.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/import_connections@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/import_connections.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/toolbar/24x24/export_connections@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/toolbar/24x24/export_connections.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/20x16/database_server@1.3x.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/20x16/database_server.png
2020-01-23 01:09:21 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:21 [main] t3.utils.u.o.ng()
ERROR: Couldn't read UUID for cm: 
2020-01-23 01:09:23 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connman/16x16/database_server@1.3x.png
2020-01-23 01:09:23 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connman/16x16/database_server.png
2020-01-23 01:09:23 [3T::Connection Manager Thread] t3.utils.connman.l.a()
WARNING: Failed to execute db.runCommand({replSetGetStatus: 1}): com.mongodb.MongoCommandException: Command failed with error 76 (NoReplicationEnabled): 'not running with --replSet' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "not running with --replSet", "code": 76, "codeName": "NoReplicationEnabled"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:243)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:214)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:116)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:109)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:56)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.l.a(Connection.java:413)
	at t3.utils.connman.l.MN(Connection.java:467)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:398)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 01:09:23 [3T::Connection Manager Thread] t3.utils.connman.l.e()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2020-01-23 01:09:29 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/color_swatches@1.3x.png
2020-01-23 01:09:29 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/color_swatches.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/user@1.3x.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/user.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/arrow_up_shorter_3t@1.3x.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/arrow_up_shorter_3t.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/arrow_down_shorter_3t@1.3x.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/arrow_down_shorter_3t.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/cross_close@1.3x.png
2020-01-23 01:09:30 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/cross_close.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/cancel@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/cancel.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/history@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/history.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/star_empty_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/star_empty_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/copy@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/copy.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/paste@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/paste.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/bullet_arrow_down@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/bullet_arrow_down.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/page-edit@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/page-edit.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/execute@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/execute.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/explain@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/explain.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/custom_search@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/custom_search.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/bullet_arrow_up@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/bullet_arrow_up.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/rewind_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/rewind_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/arrow_left_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/arrow_left_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/arrow_right_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/arrow_right_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/cog_with_bullet_arrow_down_edited@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/cog_with_bullet_arrow_down_edited.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/blank-16x16@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/blank-16x16.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/copy_multiple@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/copy_multiple.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/find@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/find.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/ff_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/ff_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/arrow_refresh@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/arrow_refresh.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/unlocked@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/unlocked.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/page_white_add@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/page_white_add.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/json-view_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/json-view_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/page_white_edit@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/page_white_edit.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/update_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/update_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/docsview/16x16/remove_tz@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/docsview/16x16/remove_tz.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/page_white_find@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/page_white_find.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-other-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-other-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-object-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-object-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-array-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-array-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-binary-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-binary-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-bool-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-bool-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-code-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-code-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-code-plus-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-code-plus-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-date-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-date-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-id-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-id-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-number-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-number-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-int32-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-int32-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-int64-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-int64-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-dec128-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-dec128-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-ref-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-ref-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-string-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-string-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-symbol-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-symbol-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-time-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-time-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-regex-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-regex-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-minkey-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-minkey-12.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/tree-type-maxkey-12@1.3x.png
2020-01-23 01:09:33 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/tree-type-maxkey-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/docs_count_was_page_number@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/docs_count_was_page_number.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/clock-select@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/clock-select.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/explain/icons/full_explain@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/explain/icons/full_explain.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/add_gt@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/add_gt.png
2020-01-23 01:09:34 [main] t3.utils.u.o.a()
ERROR: weights of CollectionTab.query_builder_sash.0EA4D7EDA5F2192F9F86EFE36CFF598C not found: java.lang.NullPointerException saved object: null
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-other-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-other-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-object-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-object-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-array-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-array-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-binary-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-binary-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-bool-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-bool-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-code-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-code-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-code-plus-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-code-plus-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-date-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-date-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-id-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-id-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-number-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-number-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-int32-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-int32-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-int64-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-int64-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-dec128-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-dec128-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-ref-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-ref-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-string-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-string-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-symbol-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-symbol-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-time-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-time-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-regex-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-regex-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-minkey-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-minkey-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/type-icon-sets/light/table-type-maxkey-12@1.3x.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/type-icon-sets/light/table-type-maxkey-12.png
2020-01-23 01:09:34 [main] t3.utils.gui.bp.a()
ERROR: We work only with square images, the original is 20 X 16
2020-01-23 01:09:35 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/connection/16x16/add_view_tz@1.3x.png
2020-01-23 01:09:35 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/connection/16x16/add_view_tz.png
2020-01-23 01:09:41 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/plus@1.3x.png
2020-01-23 01:09:41 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/plus.png
2020-01-23 01:09:41 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/minus@1.3x.png
2020-01-23 01:09:41 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/minus.png
2020-01-23 01:09:41 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fi/16x16/information-3t@1.3x.png
2020-01-23 01:09:41 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fi/16x16/information-3t.png
2020-01-23 01:10:51 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/background/12x12/hourglass@1.3x.png
2020-01-23 01:10:51 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/background/12x12/hourglass.png
2020-01-23 01:10:51 [3T::Connection Manager Thread] t3.utils.connman.l.a()
WARNING: Failed to execute db.runCommand({replSetGetStatus: 1}): com.mongodb.MongoCommandException: Command failed with error 76 (NoReplicationEnabled): 'not running with --replSet' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "not running with --replSet", "code": 76, "codeName": "NoReplicationEnabled"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:243)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:214)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:116)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:109)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:56)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.l.a(Connection.java:413)
	at t3.utils.connman.l.MN(Connection.java:467)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:398)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 01:10:51 [3T::Connection Manager Thread] t3.utils.connman.l.e()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2020-01-23 01:10:52 [3T::pooled background worker thread _0] t3.utils.s.d.b.c.run()
ERROR: t3.utils.s.d.f: JSON parse error at position 1:
Expecting an opening '{':

db.runComma

Only complete JSON documents can be parsed.
Did you maybe copy individual fields rather than only documents?
	at t3.utils.s.d.c.k.alH(JsonSource.java:195)
	at t3.utils.s.d.c.k.a(JsonSource.java:20)
	at t3.utils.s.d.c.l.alI(JsonSource.java:83)
	at t3.utils.s.d.c.l.alC(JsonSource.java:56)
	at t3.utils.s.d.b.c.run(ImporterExporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: t3.utils.q.k: Expecting an opening '{'
	at t3.utils.s.g.b.a.apj(JsonParserMongoDB.java:294)
	at t3.utils.s.g.b.a.d(JsonParserMongoDB.java:231)
	at t3.utils.s.g.b.a.a(JsonParserMongoDB.java:143)
	at t3.utils.s.d.c.k.alH(JsonSource.java:122)
	at t3.utils.s.d.c.k.a(JsonSource.java:20)
	at t3.utils.s.d.c.l.alI(JsonSource.java:83)
	at t3.utils.s.d.c.l.alC(JsonSource.java:56)
	at t3.utils.s.d.b.c.run(ImporterExporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 01:10:52 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/background/12x12/error@1.3x.png
2020-01-23 01:10:52 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/background/12x12/error.png
2020-01-23 01:10:52 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/background/12x12/running_on_error@1.3x.png
2020-01-23 01:10:52 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/background/12x12/running_on_error.png
2020-01-23 01:11:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/execute_cursor@1.3x.png
2020-01-23 01:11:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/execute_cursor.png
2020-01-23 01:11:07 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/explain_at_cursor@1.3x.png
2020-01-23 01:11:07 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/explain_at_cursor.png
2020-01-23 01:12:29 [main] t3.utils.gui.bp.getImage()
WARNING: Image doesn't exist: /t3/utils/fc/16x16/folder_explore@1.3x.png
2020-01-23 01:12:29 [main] t3.utils.gui.bp.getImage()
WARNING: Using: /t3/utils/fc/16x16/folder_explore.png
2020-01-23 01:15:03 [3T::Connection Manager Thread] t3.utils.connman.l.a()
WARNING: Failed to execute db.runCommand({replSetGetStatus: 1}): com.mongodb.MongoCommandException: Command failed with error 76 (NoReplicationEnabled): 'not running with --replSet' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "not running with --replSet", "code": 76, "codeName": "NoReplicationEnabled"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:243)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:214)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:116)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:109)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:56)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoDatabaseImpl.executeCommand(MongoDatabaseImpl.java:184)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:153)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:148)
	at com.mongodb.client.internal.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:138)
	at t3.utils.connman.l.a(Connection.java:413)
	at t3.utils.connman.l.MN(Connection.java:467)
	at t3.utils.connman.c.c.g(MongoDBConnector.java:398)
	at t3.utils.connman.c.c.j(MongoDBConnector.java:954)
	at t3.utils.connman.by.d(ConnectionManager.java:1132)
	at t3.utils.connman.by.c(ConnectionManager.java:1064)
	at t3.utils.connman.by.f(ConnectionManager.java:408)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-23 01:15:03 [3T::Connection Manager Thread] t3.utils.connman.l.e()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2020-01-23 01:15:03 [3T::pooled background worker thread _1] t3.utils.s.d.b.c.run()
ERROR: t3.utils.s.d.f: JSON parse error at position 1:
Expecting an opening '{':

db.runComma

Only complete JSON documents can be parsed.
Did you maybe copy individual fields rather than only documents?
	at t3.utils.s.d.c.k.alH(JsonSource.java:195)
	at t3.utils.s.d.c.k.a(JsonSource.java:20)
	at t3.utils.s.d.c.l.alI(JsonSource.java:83)
	at t3.utils.s.d.c.l.alC(JsonSource.java:56)
	at t3.utils.s.d.b.c.run(ImporterExporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: t3.utils.q.k: Expecting an opening '{'
	at t3.utils.s.g.b.a.apj(JsonParserMongoDB.java:294)
	at t3.utils.s.g.b.a.d(JsonParserMongoDB.java:231)
	at t3.utils.s.g.b.a.a(JsonParserMongoDB.java:143)
	at t3.utils.s.d.c.k.alH(JsonSource.java:122)
	at t3.utils.s.d.c.k.a(JsonSource.java:20)
	at t3.utils.s.d.c.l.alI(JsonSource.java:83)
	at t3.utils.s.d.c.l.alC(JsonSource.java:56)
	at t3.utils.s.d.b.c.run(ImporterExporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
